# Generated by Django 4.2.7 on 2026-04-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='current_company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='current_position',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='field_of_study',
            field=models.CharField(blank=True, help_text='e.g., Computer Science', max_length=200),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub profile URL'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='graduation_year',
            field=models.CharField(blank=True, help_text='e.g., 2020', max_length=10),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='highest_degree',
            field=models.CharField(blank=True, help_text="e.g., Bachelor's, Master's, PhD", max_length=200),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='location',
            field=models.CharField(blank=True, help_text='City, Country', max_length=200),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='portfolio_url',
            field=models.URLField(blank=True, help_text='Portfolio website URL'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='professional_summary',
            field=models.TextField(blank=True, help_text='Brief professional summary'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='university',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='years_of_experience',
            field=models.CharField(blank=True, help_text='e.g., 3 years', max_length=50),
        ),
    ]
