# Generated by Django 4.2.7 on 2026-04-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_candidateprofile_current_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='about_company',
            field=models.TextField(blank=True, help_text='Brief description about the company'),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='company_size',
            field=models.CharField(blank=True, help_text='e.g., 50-100 employees', max_length=50),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='company_website',
            field=models.URLField(blank=True, help_text='Company website URL'),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='industry',
            field=models.CharField(blank=True, help_text='e.g., Technology, Finance', max_length=100),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='location',
            field=models.CharField(blank=True, help_text='Company location', max_length=200),
        ),
    ]
